spring:
  datasource:
    url: jdbc:postgresql://10.147.17.101:5432/loginapp_db
    username: loginapp_user
    password: loginapp_password123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  thymeleaf:
    cache: false
    
server:
  port: 8080
  
logging:
  level:
    com.example.loginapp: DEBUG
    org.springframework.security: DEBUG 